general:
  logo_image: /images/cafe-web33.png
  logo-size: 16%
  mobile-logo_image: /images/cafe-web33.png
  mobile-logo-size: 100%
  explore-logo-size: 50%
  form-email:
technical:
  fonts-embed: <link rel="stylesheet" href="https://use.typekit.net/muy1sey.css">
  google-analytics-embed:
  shopify-button-embed: >-
    <div id='collection-component-1631622196816'></div> <script
    type="text/javascript"> /*<![CDATA[*/ (function () {   var scriptURL =
    'https://sdks.shopifycdn.com/buy-button/latest/buy-button-storefront.min.js';  
    if (window.ShopifyBuy) {     if (window.ShopifyBuy.UI) {      
    ShopifyBuyInit();     } else {       loadScript();     }   } else {    
    loadScript();   }   function loadScript() {     var script =
    document.createElement('script');     script.async = true;     script.src =
    scriptURL;     (document.getElementsByTagName('head')[0] ||
    document.getElementsByTagName('body')[0]).appendChild(script);    
    script.onload = ShopifyBuyInit;   }   function ShopifyBuyInit() {     var
    client = ShopifyBuy.buildClient({       domain:
    'coffee-template.myshopify.com',       storefrontAccessToken:
    '688786e53705027d8500aefae7300265',     });    
    ShopifyBuy.UI.onReady(client).then(function (ui) {      
    ui.createComponent('collection', {         id: '278785949871',         node:
    document.getElementById('collection-component-1631622196816'),        
    moneyFormat: '%24%7B%7Bamount%7D%7D',         options: {   "product": {    
    "styles": {       "product": {         "@media (min-width: 601px)":
    {           "max-width": "calc(33.33333% - 30px)",           "margin-left":
    "30px",           "margin-bottom": "50px",           "width":
    "calc(33.33333% - 30px)"         }       },       "title": {        
    "color": "#000000"       },       "button": {         "font-size":
    "16px",         "padding-top": "16px",         "padding-bottom":
    "16px",         ":hover": {           "background-color": "#de7744"        
    },         "background-color": "#f7844b",         ":focus": {          
    "background-color": "#de7744"         },         "border-radius":
    "0px"       },       "quantityInput": {         "font-size": "16px",        
    "padding-top": "16px",         "padding-bottom": "16px"       },      
    "price": {         "color": "#000000"       },       "compareAt": {        
    "color": "#000000"       },       "unitPrice": {         "color":
    "#000000"       }     },     "buttonDestination": "modal",     "contents":
    {       "options": false     },     "text": {       "button": "View
    details"     }   },   "productSet": {     "styles": {       "products":
    {         "@media (min-width: 601px)": {           "margin-left":
    "-30px"         }       }     }   },   "modalProduct": {     "contents":
    {       "img": false,       "imgWithCarousel": true,       "button":
    false,       "buttonWithQuantity": true     },     "styles": {      
    "product": {         "@media (min-width: 601px)": {           "max-width":
    "100%",           "margin-left": "0px",           "margin-bottom":
    "0px"         }       },       "button": {         "font-size":
    "16px",         "padding-top": "16px",         "padding-bottom":
    "16px",         ":hover": {           "background-color": "#de7744"        
    },         "background-color": "#f7844b",         ":focus": {          
    "background-color": "#de7744"         },         "border-radius":
    "0px"       },       "quantityInput": {         "font-size": "16px",        
    "padding-top": "16px",         "padding-bottom": "16px"       },      
    "title": {         "font-family": "Helvetica Neue, sans-serif",        
    "font-weight": "bold",         "font-size": "26px",         "color":
    "#000000"       },       "price": {         "font-family": "Helvetica Neue,
    sans-serif",         "font-weight": "normal",         "font-size":
    "18px",         "color": "#000000"       },       "compareAt": {        
    "font-family": "Helvetica Neue, sans-serif",         "font-weight":
    "normal",         "font-size": "15.299999999999999px",         "color":
    "#000000"       },       "unitPrice": {         "font-family": "Helvetica
    Neue, sans-serif",         "font-weight": "normal",         "font-size":
    "15.299999999999999px",         "color": "#000000"       },      
    "description": {         "color": "#000000"       }     },     "text":
    {       "button": "Add to cart"     }   },   "modal": {     "styles":
    {       "modal": {         "background-color": "#ededed"       }     }  
    },   "option": {     "styles": {       "label": {         "color":
    "#000000"       }     }   },   "cart": {     "styles": {       "button":
    {         "font-size": "16px",         "padding-top": "16px",        
    "padding-bottom": "16px",         ":hover": {           "background-color":
    "#de7744"         },         "background-color": "#f7844b",        
    ":focus": {           "background-color": "#de7744"         },        
    "border-radius": "0px"       },       "title": {         "color":
    "#000000"       },       "header": {         "color": "#000000"      
    },       "lineItems": {         "color": "#000000"       },      
    "subtotalText": {         "color": "#000000"       },       "subtotal":
    {         "color": "#000000"       },       "notice": {         "color":
    "#000000"       },       "currency": {         "color": "#000000"      
    },       "close": {         "color": "#000000",         ":hover":
    {           "color": "#000000"         }       },       "empty": {        
    "color": "#000000"       },       "noteDescription": {         "color":
    "#000000"       },       "discountText": {         "color": "#000000"      
    },       "discountIcon": {         "fill": "#000000"       },      
    "discountAmount": {         "color": "#000000"       },       "cart":
    {         "background-color": "#ededed"       },       "footer": {        
    "background-color": "#ededed"       }     },     "text": {       "total":
    "Subtotal",       "button": "Checkout",       "noteDescription": "Tell us if
    you are allergic or any other special requirement"     },     "contents":
    {       "note": true     }   },   "toggle": {     "styles": {      
    "toggle": {         "background-color": "#f7844b",         ":hover":
    {           "background-color": "#de7744"         },         ":focus":
    {           "background-color": "#de7744"         }       },       "count":
    {         "font-size": "16px"       }     }   },   "lineItem": {    
    "styles": {       "variantTitle": {         "color": "#000000"      
    },       "title": {         "color": "#000000"       },       "price":
    {         "color": "#000000"       },       "fullPrice": {         "color":
    "#000000"       },       "discount": {         "color": "#000000"      
    },       "discountIcon": {         "fill": "#000000"       },      
    "quantity": {         "color": "#000000"       },       "quantityIncrement":
    {         "color": "#000000",         "border-color": "#000000"      
    },       "quantityDecrement": {         "color": "#000000",        
    "border-color": "#000000"       },       "quantityInput": {         "color":
    "#000000",         "border-color": "#000000"       }     }   } },      
    });     });   } })(); /*]]>*/ </script>
  stuff-for-head-embed:
  body-scripts-embed:
  cookie-banner: false
  tracking-scripts-after-cookie-acceptance-embed:
seo:
  site_name: Demo Template | Business small descriptor
  title: Demo Template | Business small descriptor
  description: Description with main keywords about your business
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_url: https://www.instagram.com/picaronstudio
  facebook_url: https://www.facebook.com/picaronstudio
  youtube_url:
  pinterest_url:
  twitter_url:
  linkedin_url:
  instagram-embed: