general:
  logo_image: /images/demo-web24.png
  menu_image: /images/demo-web24.png
seo:
  site_name: Peruvian Bowls | Ready Meals in Brisbane
  title: Peruvian Bowls | Ready Meals in Brisbane
  description: >-
    Custom coded websites & unique brands created by a Peruvian couple and based
    in Adelaide, Australia.
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_url: https://www.instagram.com/peruvianbowls
  facebook_url: https://www.facebook.com/PeruvianBowls-102816078802645
  youtube_url:
  pinterest_url:
  twitter_url:
  linkedin_url:
  instagram-embed:
design:
  dark-text_color: '#303030'
  grey-text_color: '#4a494a'
  light-text_color: '#ffffff'
  beige-text_color: '#FCF3E2'
  red-text_color: '#EC4B33'
  blue-text_color: '#2F76B7'
  yellow-text_color: '#F9D749'
  blue_color: '#2F76B7'
  red_color: '#EC4B33'
  beige_color: '#FCF3E2'
  yellow_color: '#F9D749'
  light-red_color: '#EE887F'
  light-yellow_color: '#F5E18D'
  light_color: '#FFFDF8'
  white_color: '#ffffff'