general:
  logo_image: /images/demo-web24.png
  logo-max-width:
  menu-logo_image: /images/demo-web24.png
  form-email:
technical:
  fonts-embed:
  google-analytics-embed:
  shopify-button-embed:
  stuff-for-head-embed:
  body-scripts-embed:
  cookie-banner: false
  tracking-scripts-after-cookie-acceptance-embed:
seo:
  site_name: Demo Template | Business small descriptor
  title: Demo Template | Business small descriptor
  description: >-
    Description with main keywords about your business
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_url: https://www.instagram.com/picaronstudio
  facebook_url: https://www.facebook.com/picaronstudio
  youtube_url:
  pinterest_url:
  twitter_url:
  linkedin_url:
  instagram-embed:






