general:
  logo_image: /images/demo-web24.png
  menu_image: /images/demo-web24.png
seo:
  site_name: Peruvian Bowls | Ready Meals in Brisbane
  title: Peruvian Bowls | Ready Meals in Brisbane
  description: >-
    Custom coded websites & unique brands created by a Peruvian couple and based
    in Adelaide, Australia.
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_url: https://www.instagram.com/peruvianbowls
  facebook_url: https://www.facebook.com/PeruvianBowls-102816078802645
  youtube_url:
  pinterest_url:
  twitter_url:
  linkedin_url:
  instagram-embed:
design:
  colors:
    dark-text_color: '#303030'
    semi-dark-text_color: '#2F76B7'
    grey-text_color: '#4a494a'
    light-text_color: '#ffffff'
    warm-text_color: '#FCF3E2'
    accent-text_color: '#EC4B33'
    featured-text_color: '#F9D749'
    semi-dark_color: '#2F76B7'
    accent_color: '#EC4B33'
    warm_color: '#FCF3E2'
    featured_color: '#F9D749'
    light-accent_color: '#EE887F'
    light-featured_color: '#F5E18D'
    light_color: '#FFFDF8'
    white_color: '#ffffff'
  fonts:
    