general:
  logo_path: /images/demo-web24.png
  logo-max-width:
  menu-logo_path: /images/demo-web24.png
  form-email:
technical:
  google-fonts-embed:
  google-analytics-embed:
  shopify-button-embed:
  stuff-for-head-embed:
  body-scripts-embed:
  cookie-banner: true
  tracking-scripts-after-cookie-acceptance-embed:
seo:
  site_name: Peruvian Bowls | Ready Meals in Brisbane
  title: Peruvian Bowls | Ready Meals in Brisbane
  description: >-
    Custom coded websites & unique brands created by a Peruvian couple and based
    in Adelaide, Australia.
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_url: https://www.instagram.com/peruvianbowls
  facebook_url: https://www.facebook.com/PeruvianBowls-102816078802645
  youtube_url:
  pinterest_url:
  twitter_url:
  linkedin_url:
  instagram-embed:
design:
  colors:
    body_color:
    notification-bar_color:
    menu_color:
    mobile-menu_color:
    special-offer_color:
    testimonial-cards_color:
    sign-up_color:
    footer_color:
    banner-text_color:
    heading-text_color:
    sub-heading_color:
    text_color:
    footer-text_color:
    text-link-hover_color:
  fonts:
    text-font-family:
    heading-font-family:
    accent-font-family:
    button-font-family:
    big-heading-weight:
    heading-weight:
    sub-heading: 
    text-weight:
    button-weight:
    menu-weight:
    menu-mobile-weight:
    notification-bar-text-size:
    big-heading-text-size:
    heading-text-size:
    sub-heading-text-size: 
    text-size:
    button-text-size:
    menu-text-size:
    menu-mobile-text-size:
    notification-bar-text-size:




