general:
  logo_image: /images/demo-web24.png
  logo-max-width: 40%
  menu-logo_image: /images/candle-web13.png
  form-email:
technical:
  fonts-embed: <link rel="stylesheet" href="https://use.typekit.net/muy1sey.css">
  google-analytics-embed:
  shopify-button-embed:
  stuff-for-head-embed:
  body-scripts-embed:
  cookie-banner: false
  tracking-scripts-after-cookie-acceptance-embed:
seo:
  site_name: Demo Template | Business small descriptor
  title: Demo Template | Business small descriptor
  description: Description with main keywords about your business
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_url: https://www.instagram.com/picaronstudio
  facebook_url: https://www.facebook.com/picaronstudio
  youtube_url:
  pinterest_url:
  twitter_url:
  linkedin_url:
  instagram-embed: